let productos = [
  {
    id: 1,
    nombre: "Xiaomi Redmi Note 11",
    descripcion: "Dual SIM 128 GB azul ocaso 4 GB RAM",
    precio: 100000,
    imagen: "./images/xiaomi1.jpg",
    categoria: "Xiaomi",
    cantidad: 1,
    info: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla AMOLED de 6.43. Tiene 4 cámaras traseras de 50Mpx/8Mpx/2Mpx/2Mpx.",
  },
  {
    id: 2,
    nombre: "Xiaomi Redmi Note 10 Pro",
    descripcion: "(108 Mpx) Dual SIM 128 GB azul glaciar 6 GB RAM",
    precio: 150000,
    imagen: "./images/xiaomi2.jpg",
    categoria: "Xiaomi",
    cantidad: 1,
    info: "Con su potente procesador y memoria RAM de 8 GB tu equipo alcanzará un alto rendimiento con gran velocidad de transmisión de contenidos y ejecutará múltiples aplicaciones a la vez sin demoras.",
  },
  {
    id: 3,
    nombre: "Moto G42",
    descripcion: "128 GB color verde atlántico 4 GB RAM",
    precio: 70000,
    imagen: "./images/moto1.jpg",
    categoria: "Motorola",
    cantidad: 1,
    info: "Su memoria RAM de 4 GB permite que tu smartphone funcione de manera fluida y sin demoras al realizar distintas tareas, jugar o navegar.",
  },
  {
    id: 4,
    nombre: "Motorola Edge 30",
    descripcion: "128 GB color gris oscuro 8 GB de RAM",
    precio: 250000,
    imagen: "./images/moto2.jpg",
    categoria: "Motorola",
    cantidad: 1,
    info: "Con su potente procesador y memoria RAM de 12 GB tu equipo alcanzará un alto rendimiento con gran velocidad de transmisión de contenidos y ejecutará múltiples aplicaciones a la vez sin demoras.",
  },
  {
    id: 5,
    nombre: "Samsung Galaxy A20",
    descripcion: "32 Gb Azul Bueno (Reacondicionado)o",
    precio: 120000,
    imagen: "./images/samsung1.jpg",
    categoria: "Samsung",
    cantidad: 1,
    info: "El Samsung Galaxy A20 completa la gama Galaxy Ax entre el Galaxy A10 y el Galaxy A30. Con una pantalla Infinity-V HD+ de 6.4 pulgadas, el Galaxy A20 está potenciado por un procesador Exynos 7884 de ocho núcleos, con 3GB de memoria RAM y 32GB de almacenamiento interno.",
  },
  {
    id: 6,
    nombre: "Samsung Galaxy A33",
    descripcion: "5g 128 Gb Awesome Black 6 Gb Ram",
    precio: 135000,
    imagen: "./images/samsung2.jpg",
    categoria: "Samsung",
    cantidad: 1,
    info: "Con su potente procesador y memoria RAM de 6 GB tu equipo alcanzará un alto rendimiento con gran velocidad de transmisión de contenidos y ejecutará múltiples aplicaciones a la vez sin demoras.",
  },
];
